name: nf-core AWS test
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.
# It runs the -profile 'test' on AWS batch

on:
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS tests
    if: github.repository == 'nf-core/methylseq'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aligner: ["bismark", "bismark_hisat", "bwameth"]
        include:
          - aligner: "bismark"
            ref_index: --bismark_index results/reference_genome/BismarkIndex/
          - aligner: "bismark_hisat"
            ref_index: --bismark_index results/reference_genome/BismarkIndex/
          - aligner: "bwameth"
            ref_index: --bwa_meth_index results/reference_genome/genome.fa
    steps:
      - name: Launch workflow via tower
        uses: nf-core/tower-action@v3

        with:
          auto-update-conda: true
          python-version: 3.7
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          pipeline: ${{ github.repository }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/methylseq/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/methylseq/results-test-${{ github.sha }}"
            }
          profiles: test,aws_tower
          nextflow_config: |
            process.errorStrategy = 'retry'
            process.maxRetries = 3
      - name: Install awscli
        run: conda install -c conda-forge awscli
      - name: Start AWS batch job
        run: |
          aws batch submit-job \
          --region eu-west-1 \
          --job-name nf-core-methylseq \
          --job-queue $AWS_JOB_QUEUE \
          --job-definition $AWS_JOB_DEFINITION \
          --container-overrides '{"command": ["nf-core/methylseq", "-r '"${GITHUB_SHA}"' -profile test --aligner '"${{matrix.aligner}}"' --outdir s3://'"${AWS_S3_BUCKET}"'/methylseq/results-'"${GITHUB_SHA}"'/'"${{matrix.aligner}}"/' -w s3://'"${AWS_S3_BUCKET}"'/methylseq/work-'"${GITHUB_SHA}"'/'"${{matrix.aligner}}" -with-tower"], "environment": [{"name": "TOWER_ACCESS_TOKEN", "value": "'"$TOWER_ACCESS_TOKEN"'"}]}'
