name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
      - dsl2
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/methylseq') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.3"
          - "latest-everything"
        aligner:
          - "bismark"
          - "bismark_hisat"
          - "bwameth"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Test - Single End
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,docker --aligner ${{matrix.aligner}} --save_reference --outdir ./results

      - name: Test - Single End with index
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,docker --aligner ${{matrix.aligner}} ${{matrix.ref_index}} --outdir ./results

      - name: Test - Single End RRBS
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,docker --aligner ${{matrix.aligner}} --skip_trimming --rrbs --outdir ./results

      - name: Test - Paired End with index
        run: nextflow run ${GITHUB_WORKSPACE} -profile test_paired,docker --aligner ${{matrix.aligner}} ${{matrix.ref_index}} --outdir ./results
